version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: task_notes_db
    environment:
      POSTGRES_DB: task_notes_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FastAPI Application
  web:
    build: .
    container_name: task_notes_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:mypassword123@db:5432/task_notes_dashboard
      SECRET_KEY: your-docker-secret-key-here-make-it-strong
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: